export const fallbackBranding = {
  id: 'fallback-restaurant',
  name: 'FlameGrill',
  tagline: 'Premium Burgers & Grills Since 2018',
  logo: '',
  phone: '+1 555-123-4567',
  email: 'hello@flamegrill.com',
  address: '123 Main Street, Downtown, New York, NY 10001',
  openHours: 'Mon-Thu: 10AM-10PM | Fri-Sat: 10AM-12AM | Sun: 11AM-9PM',
  primaryColor: '#DC2626',
  secondaryColor: '#1E3A5F',
  accentColor: '#F59E0B',
  currency: '$',
  currencyCode: 'USD',
  deliveryFee: 2.99,
  minOrder: 15.0,
  deliveryRadius: 10.0,
  socialFacebook: 'https://facebook.com/flamegrill',
  socialInstagram: 'https://instagram.com/flamegrill',
  socialTwitter: 'https://twitter.com/flamegrill',
  heroImages: JSON.stringify([
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&h=600&fit=crop',
    'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&h=600&fit=crop',
    'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=1200&h=600&fit=crop',
  ]),
  termsLink: '/terms',
  privacyLink: '/privacy',
};

export const fallbackCategories = [
  {
    id: 'cat-burgers',
    name: 'Signature Burgers',
    description: 'Our award-winning handcrafted burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    sortOrder: 1,
    isActive: true,
    _count: { items: 3 },
  },
  {
    id: 'cat-chicken',
    name: 'Chicken & Wings',
    description: 'Crispy, juicy, and full of flavor',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=300&fit=crop',
    sortOrder: 2,
    isActive: true,
    _count: { items: 2 },
  },
  {
    id: 'cat-sides',
    name: 'Sides & Snacks',
    description: 'Perfect companions to your meal',
    image: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=400&h=300&fit=crop',
    sortOrder: 3,
    isActive: true,
    _count: { items: 2 },
  },
  {
    id: 'cat-drinks',
    name: 'Beverages',
    description: 'Refreshing drinks for every taste',
    image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=400&h=300&fit=crop',
    sortOrder: 4,
    isActive: true,
    _count: { items: 1 },
  },
];

const categoryById = Object.fromEntries(fallbackCategories.map((category) => [category.id, category]));

const variation = (itemId: string, name = 'Regular', isDefault = true) => ({
  id: `${itemId}-variation-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  name,
  priceMod: 0,
  isDefault,
});

const addon = (itemId: string, name: string, price: number) => ({
  id: `${itemId}-addon-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  name,
  price,
});

export const fallbackMenuItems = [
  {
    id: 'item-classic-flame',
    name: 'The Classic Flame',
    description:
      'Our signature Angus beef patty, aged cheddar, crispy lettuce, tomatoes, pickles, and FlameGrill sauce on a toasted brioche bun.',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=400&fit=crop',
    categoryId: 'cat-burgers',
    category: categoryById['cat-burgers'],
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    calories: 750,
    prepTime: 15,
    variations: [variation('item-classic-flame', 'Single'), { ...variation('item-classic-flame', 'Double', false), priceMod: 4.5 }],
    addons: [addon('item-classic-flame', 'Extra Cheese', 1.5), addon('item-classic-flame', 'Bacon', 2)],
    _count: { reviews: 0 },
  },
  {
    id: 'item-smoky-bbq',
    name: 'Smoky BBQ Blaze',
    description:
      'Char-grilled beef patty glazed with smoky BBQ sauce, crispy onion rings, smoked gouda, and tangy coleslaw.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500&h=400&fit=crop',
    categoryId: 'cat-burgers',
    category: categoryById['cat-burgers'],
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    calories: 820,
    prepTime: 18,
    variations: [variation('item-smoky-bbq')],
    addons: [addon('item-smoky-bbq', 'Extra BBQ Sauce', 0.5), addon('item-smoky-bbq', 'Double Patty', 4)],
    _count: { reviews: 0 },
  },
  {
    id: 'item-veggie-burger',
    name: 'Garden Veggie Burger',
    description:
      'House-made quinoa and black bean patty with avocado, sprouts, tomato, and herb garlic aioli on a whole wheat bun.',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1520072959219-c595e6cdc07e?w=500&h=400&fit=crop',
    categoryId: 'cat-burgers',
    category: categoryById['cat-burgers'],
    isAvailable: true,
    isPopular: false,
    isNew: true,
    isSpicy: false,
    isVegetarian: true,
    calories: 520,
    prepTime: 14,
    variations: [variation('item-veggie-burger')],
    addons: [addon('item-veggie-burger', 'Extra Avocado', 1.75), addon('item-veggie-burger', 'Feta Cheese', 1.25)],
    _count: { reviews: 0 },
  },
  {
    id: 'item-crispy-chicken',
    name: 'Crispy Chicken Burger',
    description:
      'Buttermilk-brined chicken breast, hand-breaded and fried with pickles and spicy mayo on a buttery bun.',
    price: 11.49,
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=500&h=400&fit=crop',
    categoryId: 'cat-chicken',
    category: categoryById['cat-chicken'],
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    calories: 680,
    prepTime: 16,
    variations: [variation('item-crispy-chicken', 'Original'), variation('item-crispy-chicken', 'Spicy', false)],
    addons: [addon('item-crispy-chicken', 'Cheese', 1), addon('item-crispy-chicken', 'Extra Spicy Mayo', 0.5)],
    _count: { reviews: 0 },
  },
  {
    id: 'item-buffalo-wings',
    name: 'Buffalo Wings (8pc)',
    description: 'Eight crispy fried chicken wings tossed in buffalo sauce. Served with dip and celery sticks.',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500&h=400&fit=crop',
    categoryId: 'cat-chicken',
    category: categoryById['cat-chicken'],
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: true,
    isVegetarian: false,
    calories: 890,
    prepTime: 20,
    variations: [variation('item-buffalo-wings', 'Medium'), variation('item-buffalo-wings', 'Hot', false)],
    addons: [addon('item-buffalo-wings', 'Ranch Dip', 0.5), addon('item-buffalo-wings', '4 Extra Wings', 4.5)],
    _count: { reviews: 0 },
  },
  {
    id: 'item-loaded-fries',
    name: 'Loaded Flame Fries',
    description: 'Crispy golden fries topped with cheese sauce, crispy bits, jalapenos, and sour cream.',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=500&h=400&fit=crop',
    categoryId: 'cat-sides',
    category: categoryById['cat-sides'],
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: false,
    calories: 650,
    prepTime: 10,
    variations: [variation('item-loaded-fries')],
    addons: [addon('item-loaded-fries', 'Extra Cheese', 1), addon('item-loaded-fries', 'Extra Jalapenos', 0.75)],
    _count: { reviews: 0 },
  },
  {
    id: 'item-onion-rings',
    name: 'Crispy Onion Rings',
    description: 'Thick-cut onion rings in a seasoned crispy batter. Light, crunchy, and irresistible.',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=500&h=400&fit=crop',
    categoryId: 'cat-sides',
    category: categoryById['cat-sides'],
    isAvailable: true,
    isPopular: false,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    calories: 420,
    prepTime: 8,
    variations: [variation('item-onion-rings')],
    addons: [addon('item-onion-rings', 'BBQ Dip', 0.5), addon('item-onion-rings', 'Chipotle Mayo', 0.5)],
    _count: { reviews: 0 },
  },
  {
    id: 'item-milkshake',
    name: 'Premium Milkshake',
    description: 'Thick, creamy milkshake made with real ice cream. Available in classic flavors.',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&h=400&fit=crop',
    categoryId: 'cat-drinks',
    category: categoryById['cat-drinks'],
    isAvailable: true,
    isPopular: true,
    isNew: false,
    isSpicy: false,
    isVegetarian: true,
    calories: 450,
    prepTime: 5,
    variations: [variation('item-milkshake', 'Chocolate'), variation('item-milkshake', 'Vanilla', false)],
    addons: [addon('item-milkshake', 'Whipped Cream', 0.5), addon('item-milkshake', 'Extra Syrup', 0.75)],
    _count: { reviews: 0 },
  },
];

export const fallbackDeliveryAreas = [
  {
    id: 'area-saddar',
    name: 'Saddar',
    slug: 'saddar',
    isActive: true,
    sortOrder: 1,
    latitude: 24.8607,
    longitude: 67.0011,
    radiusKm: 3.0,
  },
  {
    id: 'area-burns-road',
    name: 'Burns Road',
    slug: 'burns-road',
    isActive: true,
    sortOrder: 2,
    latitude: 24.8601,
    longitude: 67.0103,
    radiusKm: 2.5,
  },
  {
    id: 'area-gulshan-e-iqbal',
    name: 'Gulshan-e-Iqbal',
    slug: 'gulshan-e-iqbal',
    isActive: true,
    sortOrder: 3,
    latitude: 24.9138,
    longitude: 67.0936,
    radiusKm: 4.0,
  },
  {
    id: 'area-gulshan-e-johar',
    name: 'Gulshan-e-Johar',
    slug: 'gulshan-e-johar',
    isActive: true,
    sortOrder: 4,
    latitude: 24.928,
    longitude: 67.0955,
    radiusKm: 3.5,
  },
];
